cernopendata/views.py
# -*- coding: utf-8 -*-

"""cernopendata base Invenio configuration."""

from __future__ import absolute_import, print_function

import functools
import json
import pkg_resources

from flask import Blueprint, abort, current_app, escape, render_template, request, url_for
from flask_babelex import lazy_gettext as _
from flask_breadcrumbs import default_breadcrumb_root, register_breadcrumb
from flask_menu import register_menu
from jinja2.exceptions import TemplateNotFound
from speaklater import make_lazy_string
from werkzeug import secure_filename


blueprint = Blueprint(
    'cernopendata',
    __name__,
    template_folder='templates',
    static_folder='static',
)

default_breadcrumb_root(blueprint, '.')

@blueprint.errorhandler(TemplateNotFound)
def template_not_found(err):
    """Log missing template."""
    current_app.logger.exception('Please check missing template.')
    abort(404)
    # return 'Template not found!', 404


def lazy_title(text, *args):
    """Make tranlated string with escaped values from request view args."""
    return _(text, **{key: make_lazy_string(
        lambda: escape(request.view_args.get(key, ''))
    ) for key in args})


@blueprint.route('/')
@register_menu(blueprint, 'main.education', _('Education'), order=2,
               active_when=lambda: False,
               endpoint_arguments_constructor=lambda: {'_anchor': 'education'})
@register_menu(blueprint, 'main.research', _('Research'), order=3,
               active_when=lambda: False,
               endpoint_arguments_constructor=lambda: {'_anchor': 'research'})
@register_breadcrumb(blueprint, '.', _('Home'))
@register_breadcrumb(blueprint, '.education', _('Education'),
                     endpoint_arguments_constructor=lambda: {
                         '_anchor': 'education'})
@register_breadcrumb(blueprint, '.research', _('Research'),
                     endpoint_arguments_constructor=lambda: {
                         '_anchor': 'education'})
def index():
    """Home Page."""
    return render_template('cernopendata/index.html')


@blueprint.route('/education')
@blueprint.route('/education/<string:experiment>')
@register_breadcrumb(blueprint, '.education.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def education(experiment=None):
    """Display education pages."""
    if experiment not in current_app.config['OPENDATA_EXPERIMENTS']:
        abort(404)

    return render_template('cernopendata/education.html',
                           experiment=experiment)



@blueprint.route('/research')
@blueprint.route('/research/<string:experiment>')
@register_breadcrumb(blueprint, '.research.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def research(experiment=None):
    import os.path, pkg_resources

    def file_exists(filename):
        filepath = pkg_resources.resource_filename('cernopendata.base', filename)
        return os.path.isfile(filepath)

    def splitting(value, delimiter='/'):
        return value.split(delimiter)

    current_app.jinja_env.filters['splitthem'] = splitting
    current_app.jinja_env.filters['file_exists'] = file_exists

    exp_colls, exp_names = get_collections()

    if experiment not in exp_names :
        return render_template('index_scrollspy.html', entry = 'research', exp_colls = exp_colls, exp_names = exp_names)

    return render_template('research.html',
                            experiment=experiment, exp_colls = exp_colls, exp_names = exp_names)


@blueprint.route('/visualise/events/<string:experiment>')
def visualise_events(experiment = 'CMS'):

    exp_names = get_collection_names(['ALICE', 'LHCb', 'ATLAS'])

    breadcrumbs = [{},{'url':'.education','text':'Education'},\
                        {'url':'.education','text':'Visualise Events'}]
    try:
        return render_template('visualise_events.html', experiment = experiment, exp_names = exp_names, breadcrumbs = breadcrumbs)
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/visualise/histograms/<string:experiment>')
def visualise_histo(experiment='CMS'):
    exp_colls, exp_names = get_collections()

    breadcrumbs = [{}, {'url':'.education','text':'Education'},
                        {'url':'.education','text':'Visualise Histograms'}]

    try:
        return render_template('visualise_histograms.html', experiment = experiment, exp_names = exp_names, breadcrumbs = breadcrumbs)
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/getting-started')
@register_breadcrumb(blueprint, '.get_started', _('Get Started'))
def get_started():
    """Render index of getting started tutorials."""
    return render_template('cernopendata/get_started/index.html')


@blueprint.route('/getting-started/<string:experiment>')
@blueprint.route('/getting-started/<string:experiment>/<string:year>')
@register_breadcrumb(blueprint, '.get_started.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def get_started_experiment(experiment=None, year=None):
    """Render getting started tutorials."""
    return render_template(
        'cernopendata/get_started/experiment_{0}.html'.format(
            experiment.lower()
        ), experiment=experiment, year=year,
    )


@blueprint.route('/resources')
@register_breadcrumb(blueprint, '.education.resources',
                     _('Learning Resources'))
def resources():
    """Render index of resources."""
    return render_template('cernopendata/resources.html')


@blueprint.route('/VM')
@blueprint.route('/VM/')
@register_breadcrumb(blueprint, '.vm', _('Virtual Machines'))
def vm():
    """Display experiment VMs."""
    return render_template('cernopendata/vm/index.html')


@blueprint.route('/VM/<string:experiment>', defaults={'year': None})
@blueprint.route('/VM/<string:experiment>/<string:year>')
@register_breadcrumb(blueprint, '.vm.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def vm_experiment(experiment, year):
    """Display details about experiment VMs."""
    return render_template(
        'cernopendata/vm/experiment_{0}.html'.format(experiment.lower()),
        year=year,
    )


@blueprint.route('/VM/<string:experiment>/validation/report')
@register_breadcrumb(blueprint, '.vm.validation_report',
                     lazy_title('%(experiment)s Validation Report',
                                'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def validation_report(experiment):
    """Display default abourt experiment validation report."""
    return render_template([
        'cernopendata/vm/validation_{0}.html'.format(experiment.lower()),
        'cernopendata/vm/validation.html',
    ], experiment=experiment)


def about_menu(*args):
    """Generate menu decorator."""
    def decorator(f):
        for order, key in enumerate(args):
            def arguments(key):
                return lambda: {'page': key}
            f = register_menu(
                blueprint, 'main.about.{0}'.format(key),
                _('%(experiment)s Open Data', experiment=key), order=order+1,
                endpoint_arguments_constructor=arguments(key)
            )(f)
        return f
    return decorator


def about_breadcrumbs():
    """Generate breadcrumbs for about pages."""
    key = request.view_args.get('page')
    breadcrumbs = [{'url': url_for('cernopendata.about'), 'text': _('About')}]
    if key:
        breadcrumbs.append({
            'url': url_for('cernopendata.about', experiment=key),
            'text': _('%(experiment)s Open Data', experiment=key),
        })
    return breadcrumbs


@blueprint.route('/about')
@blueprint.route('/about/<page>')
@register_menu(blueprint, 'main.about', _('About'), order=1)
@register_menu(blueprint, 'main.about.this', _('This Portal'), order=0)
@about_menu('CMS', 'ALICE', 'ATLAS', 'LHCb')
@register_breadcrumb(blueprint, '.about', _('About'),
                     dynamic_list_constructor=about_breadcrumbs)
def about(page='index'):
    """Render about page."""
    return render_template([
        'cernopendata/about/{0}.html'.format(
            secure_filename(page.lower()).replace('/', '-')
        ),
        'cernopendata/about/index.html',
    ])


@blueprint.route('/terms-of-use')
@register_breadcrumb(blueprint, '.terms', _('Terms of Use'))
def terms():
    """Render terms of use."""
    return render_template('cernopendata/terms_of_use.html')


@blueprint.route('/privacy-policy')
@register_breadcrumb(blueprint, '.privacy', _('Privacy Policy'))
def privacy():
    """Render privacy policy."""
    return render_template('cernopendata/privacy_policy.html')


@blueprint.route('/experiments')
def collections():
    import json, pkg_resources
    filepath = pkg_resources.resource_filename('cernopendata.base', 'templates/helpers/text/testimonials.json')
    with open(filepath,'r') as f:
        testimonials = json.load(f)

    def splitting(value, delimiter='/'):
        return value.split(delimiter)

    current_app.jinja_env.filters['splitthem'] = splitting

    exp_colls, exp_names = get_collections()

    return render_template('index_scrollspy.html', testimonials = testimonials, exp_colls = exp_colls, exp_names = exp_names)


@blueprint.route('/glossary', methods=['GET', 'POST'])
@register_menu(blueprint, 'main.about.glossary', _('Glossary'), order=90)

cernopendata/templates/data.html
{% extends "page.html" %}

{% block body %}

  <section class="infobar">
    <div class="container">
      <a href="{{ url_for('news') }}"><h3>Data</h3></a>
    </div>
  </section>

  <section class="content">

  </section>


{% endblock %}

cernopendata/templates/data_vms.html
{% extends "page.html" %}



{% block body %}

  <style>

    #vm_howto_content > .row {
      margin-bottom: 20px;
    }

    .tab-pane .about .title {
      font-weight: 600;
      font-size: 28px;
      padding-bottom: 30px;
    }

    .coll-exp .thumb {
      border-bottom: 1px solid #dfdfdf;
      padding-bottom: 20px;
    }
    .coll-exp .thumb img {
      height: 120px;
      padding: 5px;
      border-radius: 5px;
      font-size: 30px;
      font-weight: 100px;
    }

    .coll-exp .title span{
      float: left;
      font-size: 16px;
      font-weight: 400;

    }
    .coll-exp .other {
      padding-bottom: 25px;
      height: 100%;
      max-height: 150px;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .coll-exp .other span {
      height: 120px;
      text-overflow: ellipsis;
      overflow: hidden;
      display: block;
    }
    .coll-exp .exp-name {
      padding: 20px;
      font-size: 26px;
      font-weight: 100;
      color: #657580;
    }

    .coll-exp {
      background-color: #f4f4f4;
      padding: 30px;
      text-align: center;
      height: auto;
      display: inline-block;
      font-weight: 100;
      border-radius: 5px;
      color: #657580;
      margin-bottom: 20px;
      width: 100%;
    }

  </style>

  {% import 'helpers/general.html' as gen_utils %}
  {% with collection = 0 %}
    {% include 'search/form/index.html' %}
  {% endwith %}

  <section class="infobar">
    <div class="container">
      {{ gen_utils.get_breadcrumbs(breadcrumbs, exp, exp_names) }}
    </div>
  </section>

  <section class="general content">
    <div class="container">
      
      <div class="tab-content">
        <div class="tab-pane fade {% if exp not in exp_names %} in active {% endif %}" id="general">
          <div class="gen-header">
            <h1>CERN Virtual Machines allow you to run Scientific Linux on any operating system and access the CERN working environments and software tools.</h1>
          </div>
          <div class="row">
            {% for e in exp_names %}
            <div class="col-md-6">
              <a href="{{ url_for((request.path|splitthem)[1]+'/'+e) }}">
                <div class="coll-exp">
                  <div class="top col-md-12">
                    <div class="col-md-6 col-md-offset-3 thumb"><img src="{{ url_for('static', filename='img/'+e+'.gif') }}" alt="" class="img-cirle center-block"></div>
                    <div class="col-md-12 exp-name">{{e}} Virtual Machines</div>
                  </div>
                </div>
              </a>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="tab-pane fade {% if exp == 'CMS' %} in active {% endif %}" id="CMS">
          {% include 'helpers/text/vms_cms_page.html' %}
        </div>
        <div class="tab-pane fade {% if exp == 'ALICE' %} in active {% endif %}" id="ALICE">
          {% include 'helpers/text/vms_alice_page.html' %}
        </div>
        <div class="tab-pane fade {% if exp == 'LHCb' %} in active {% endif %}" id="LHCb">
          {% include 'helpers/text/vms_lhcb_page.html' %}
        </div>
      </div>

    </div>

  </section>


{% endblock %}

{%- block javascript %}
{{super()}}
<script>
$(document).ready(function() {
  // add a hash to the URL when the user clicks on a tab
  $('a[data-toggle="tab"]').on('click', function(e) {
    history.pushState(null, null, $(this).attr('href'));
  });
  // navigate to a tab when the history changes
  window.addEventListener("popstate", function(e) {
    var activeTab = $('[href="' + location.pathname + '"][data-toggle="tab"]');
    if (activeTab.length) {
      activeTab.tab('show');
    } else {
      $('.nav-tabs a:first').tab('show');
    }
  });
});
</script>
{% endblock %}

cernopendata/templates/get_started_CMS.html
<div class="yeartabs-container">
  <div class="yeartabs">
    <div {% if year == '2010' %}class="in active"{% endif %}><a data-toggle="tab"  data-target="#year2010" href="{{url_for('.get_started', exp='CMS', year='2010')}}">2010</a></div>
    <div {% if year == '2011' or year==None %}class="in active"{% endif %}><a data-toggle="tab" data-target="#year2011" href="{{url_for('.get_started', exp='CMS', year='2011')}}">2011</a></div>
  </div>  
</div>

<div class="tab-content">
  <div id="year2010" class="tab-pane fade {% if year == '2010' %} in active {% endif %}">
    {% include 'get_started_CMS_2010.html' ignore missing %}
  </div>
  <div id="year2011" class="tab-pane fade {% if year == '2011' or year==None %} in active {% endif %}">
    {% include 'get_started_CMS_2011.html' ignore missing %}
  </div>
</div>

cernopendata/templates/header.html
<header id="od-header">
  <nav class="navbarOutter navbar navbar-static-top" role="navigation">
    <!--            <div class="topnav">
    <div class="container">
    <div class="inner">
    <ul>
    <ul>
    <li class="active">EN</li>
    <a href="#"><li>FR</li></a>
    <a href="#"><li>DE</li></a>
    <a href="#"><li>..</li></a>
    </ul>
    </ul>
    </div>
    <div class="social">
    {% if not (current_user.is_guest) %}
      <a  class="logoutBut" href="{{ url_for('webaccount.logout') }}">LOGOUT</a>
    {% endif %}
    <a href="#"><span class="fa fa-facebook"></span></a>
    <a href="#"><span class="fa fa-twitter"></span></a>
    <a href="#"><span class="fa fa-youtube-play"></span></a>
    </div>
    </div>
    </div> -->
    <div class="midnav">
      <div class="container">
        <div class="row">
          <div class="logo col-xs-12 col-sm-4  col-md-5">
            <a href="{{ url_for('cernopendata.middle') }}">
              <img src="{{ url_for('static', filename='img/home/opendata_logo.svg') }}" alt="" style="margin-left:-40px;margin-top:-10px;height:60px;">
            </a>
            <div id="st-trigger-effects" class="pull-right mob-toggle visible-xs visible-sm">
              <button  type="button" class="navbar-toggle" data-effect="st-effect-3" data-toggle="collapse" data-target="[id*='navbarCollapse']">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
          </div>
          <img src="{{ url_for('static', filename='img/demo.png') }}" alt="" style="position:absolute;left:40%;top:0;width:200px;">
          <div  class="innernav col-md-7">
            <!-- Collection of nav links and other content for toggling -->
            <div id="navbarCollapse" class="collapse navbar-collapse">
              <ul class="nav navbar-nav pull-right">
                <li class="dropdown">
                  <a href="{{ url_for('about') }}" data-toggle="dropdown" class="disabled">ABOUT</a>
                  <ul class="dropdown-menu" role="menu">
                    <li class="col-md-12" role="presentation"><a href="{{ url_for('about') }}">This Portal</a></li>
                    <li class="col-md-12" role="presentation"><a href="{{ url_for('about/CMS') }}">CMS Open Data</a></li>
                    <li class="col-md-12" role="presentation"><a href="{{ url_for('about/ALICE') }}">ALICE Open Data</a></li>
                    <li class="col-md-12" role="presentation"><a href="{{ url_for('about/ATLAS') }}">ATLAS Open Data</a></li>
                    <li class="col-md-12" role="presentation"><a href="{{ url_for('about/LHCb') }}">LHCb Open Data</a></li>
                    <li class="col-md-12" role="presentation"><a href="{{ url_for('cernopendata.glossary') }}">Glossary</a></li>
                    <li class="col-md-12" role="presentation"><a href="{{ url_for('cernopendata.news') }}">News</a></li>
                  </ul>
                </li>
                <li><a href="{{ url_for('search') }}">SEARCH</a></li>
                <li><a href="{% if home==true %}#education" onclick="history.pushState({},'','education')" {%else%}{{ url_for('cernopendata.education') }}"{% endif %}>EDUCATION</a></li>
                <li><a href="{% if home==true %}#research" onclick="history.pushState({},'','research')" {%else%}{{ url_for('cernopendata.research') }}"{%endif%}">RESEARCH</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

cernopendata/templates/header_with_searchbar.html
<header id="od-header">
  <nav class="navbarOutter navbar navbar-static-top" role="navigation">
    <!--            <div class="topnav">
    <div class="container">
    <div class="inner">
    <ul>
    <ul>
    <li class="active">EN</li>
    <a href="#"><li>FR</li></a>
    <a href="#"><li>DE</li></a>
    <a href="#"><li>..</li></a>
    </ul>
    </ul>
    </div>
    <div class="social">
    {% if not (current_user.is_guest) %}
      <a  class="logoutBut" href="{{ url_for('webaccount.logout') }}">LOGOUT</a>
    {% endif %}
    <a href="#"><span class="fa fa-facebook"></span></a>
    <a href="#"><span class="fa fa-twitter"></span></a>
    <a href="#"><span class="fa fa-youtube-play"></span></a>
    </div>
    </div>
    </div> -->
    <div class="midnav">
      <div class="container">
        <div class="logo col-xs-6 col-sm-4 no-padding">
          <a href="{{ url_for('cds.index') }}"><div class="logoimg">
            <div class="sp1">CERN</div>
            <div class="sp2">OPENDATA</div>
          </div></a>
        </div>
        <div  class="innernav">
          <div id="st-trigger-effects" class="pull-right mob-toggle visible-xs visible-sm">
            <button  type="button" class="navbar-toggle" data-effect="st-effect-3" data-toggle="collapse" data-target="[id*='collapse-toggle-nav']">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <!-- Collection of nav links and other content for toggling -->
          <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <a href="#"><li>MENU1</li></a>
              <a href="#"><li>MENU2</li></a>
              <a href="#"><li>INFO</li></a>
              <a href="#"><li>MORE</li></a>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>
  {% include 'search/form/index.html' %}
</header>

cernopendata/templates/news_page.html
{%- extends 'page.html' %}

{% import 'data/news_db.html' as n %}
{% import 'helpers/general.html' as gen_utils %}

{% macro date_to_text(date) %}
  <span class="date">4 days ago</span>
{% endmacro %}

{% macro tag_box(name, classes) %}
  {% block tag_box scoped%}
    <a href="#" class="tag-box {{classes}}">
      <span>#{{name}}</span>
    </a>
  {% endblock %}
{% endmacro %}

{% block body %}


  {% set nn = n.news[news_id-1] %}
  <section class="infobar">
    <div class="container">
      {{gen_utils.get_breadcrumbs(breadcrumbs)}}
    </div>
  </section>
  <section class="news-preview">
    <div class="title">
      <div class="container">
        <div class="info pull-left">
          <div class="inner-title">
            <div>{{ nn[0] }}</div>
          </div>
          <div class="details">posted by {{ nn[2] }}, {{ nn[4] }} </div>
        </div>
        <div class="more pull-right">
          <div class="category">
            {% for tag in nn[3][2] %}
              <a class="tag-box" href=""><span>#{{ tag }}</span></a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="body">
        {{ nn[1]|safe }}
        <div class="links">
          {% for link in nn[3][1] %}
            <a href="{{ link }}">{{ link }}</a><br/>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

{% endblock body %}

cernopendata/templates/page_base.html
{#
# This file is part of CERN Open Data Portal.
# Copyright (C) 2012, 2013, 2014 CERN.
#
# CERN Open Data Portal is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# CERN Open Data Portal is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}

{%- from "_macros.html" import flashed_messages with context -%}

{%- block global_bundles %}
  {%- include "base/bundles.html" %}
{%- endblock %}

{%- block page -%}
{%- if not no_pageheader -%}
{%- block page_top -%}
<!DOCTYPE html>
<html
{%- if g.ln %} lang="{{ g.ln|safe }}"
  {%- if is_language_rtl(g.ln) %} dir="rtl"{% endif %}
{%- endif %}>
<head>
  {%- block head %}
  {%- block head_meta %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{{ title+' - ' if title }}{{ config.CFG_SITE_NAME_INTL[g.ln] }}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {%- if description %}<meta name="description" content="{{ description }}" />{% endif %}
  {%- if keywords %}<meta name="keywords" content="{{ keywords }}" />{% endif %}
  {%- if config.get('CFG_GOOGLE_SITE_VERIFICATION', None) %}
    {%- for google_id in config.CFG_GOOGLE_SITE_VERIFICATION %}
  <meta name="google-site-verification" content="{{google_id}}"/>
    {%- endfor %}
  {%- endif %}
  {%- endblock head_meta %}

  {%- block head_links %}
  <link rel="author" href="mailto:{{ config.CFG_SITE_SUPPORT_EMAIL }}"/>
  <link rel="canonical" href="{{ canonical_url }}"/>
  {%- block head_links_langs %}{%- for alt_ln, alternate_url in alternate_urls.items() %}
  <link rel="alternate" hreflang="{{ alt_ln }}" href="{{ alternate_url }}"/>
  {%- endfor %}{%- endblock %}
  <link rel="alternate" type="application/rss+xml"
        {{- ' ' -}}
        title="{{ config.CFG_SITE_NAME }} RSS"
        {{- ' ' -}}
        href="{{ url_for('rss') }}" />
  <link rel="search" type="application/opensearchdescription+xml"
        {{- ' ' -}}
        href="{{ url_for('opensearchdescription') }}"
        {{- ' ' -}}
        title="{{ config.CFG_SITE_NAME }}"/>
  <link rel="unapi-server" type="application/xml" title="unAPI"
        {{- ' ' -}}
        href="{{ url_for('unapi') }}"/>
  {%- if linkbackTrackbackLink %}{{ linkbackTrackbackLink }}{%- endif %}
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}"/>
  {%- block head_apple_icons %}
  {%- for size in [144, 114, 72, 57] %}
    {%- set icon_name = 'apple-touch-icon-%d-precomposed.png' | format(size) %}
  <link rel="apple-touch-icon-precomposed" sizes="{{ size }}x{{ size }}"
        {{- ' ' -}}
        href="{{ url_for('static', filename=icon_name) }}"/>
  {%- endfor %}
  {%- endblock head_apple_icons %}
  {%- endblock head_links %}

  {%- block header %}
    {{- metaheaderadd | safe }}
    {%- block metaheader %}{% endblock metaheader %}
  {%- endblock header %}

  {%- block _top_assets %}
    {%- block global_stylesheets %}
      {%- include "base/stylesheets.html" %}
    {%- endblock %}
  {%- endblock %}
  {%- block css %}{% endblock %}
  {%- endblock head %}
</head>
<body{% if body_css_classes %} class="{{ body_css_classes|join(' ') }}"{% endif %}{% if g.ln %} lang="{{ g.ln.split('_', 1)[0]|safe }}"{% if rtl_direction %} {{ rtl_direction|safe }}{% endif %}{% endif %} itemscope itemtype="http://schema.org/WebPage" {% block body_attributes %}{% endblock %}>
{%- block body_start %}{% endblock body_start %}
{%- block page_header -%}
  <div id="wrap">
    <header>
      <!-- replaced page header -->
      {% block headerbox %}
        {% include 'header.html' %}
      {% endblock headerbox %}
      <!-- end replaced page header -->
      {% block breadcrumb %}
      {%- include 'breadcrumbs.html' -%}
      {% endblock breadcrumb %}
      {% block pageheaderadd %}{{ pageheaderadd|safe }}{% endblock pageheaderadd %}
    </header>
{%- endblock page_header -%}
{%- endblock page_top -%}
{%- endif -%}

{%- if not no_pagebody -%}
{%- block page_body -%}
    <div class="container">
      {% block title %}
        {% if title %}
          <div class="page-header">
            <h1>{{ title }}</h1>
          </div>
        {% endif %}
      {% endblock title %}
      {{ flashed_messages() }}
      {%- block body %}
        {{ body }}
      {%- endblock body %}
    </div>
{%- endblock page_body %}
{%- endif %}

{%- if not no_pagefooter -%}
{%- block page_bottom -%}
{%- block page_footer %}
    <div id="push"></div>
  </div>{# end wrap #}
<footer id="footer">
  <div class="container">
    {%- block pagefooteradd %}
      {{- pagefooteradd | safe }}
    {%- endblock pagefooteradd %}
  </div>
  {# replaced page footer #}
  {%- include 'footer.html' %}
</footer>
{%- endblock page_footer %}
{%- block _bottom_assets %}
  {% block global_scripts %}
    {%- include "base/scripts.html" %}
  {% endblock %}
{%- endblock %}
{%- block javascript %}{% endblock %}
{%- block body_end %}{% endblock %}
</body>
</html>
{%- endblock page_bottom -%}
{%- endif -%}
{%- endblock page -%}

cernopendata/templates/visualise.html
{% extends "page.html" %}

{% block body %}

  <section class="infobar">
    <div class="container">
      <a href="{{ url_for('news') }}"><h3>Visualise</h3></a>
    </div>
  </section>

  <section class="content">

  </section>


{% endblock %}