cernopendata/views.py
# -*- coding: utf-8 -*-

"""cernopendata base Invenio configuration."""

from __future__ import absolute_import, print_function

import functools
import json
import pkg_resources

from flask import Blueprint, abort, current_app, escape, render_template, request, url_for
from flask_babelex import lazy_gettext as _
from flask_breadcrumbs import default_breadcrumb_root, register_breadcrumb
from flask_menu import register_menu
from jinja2.exceptions import TemplateNotFound
from speaklater import make_lazy_string
from werkzeug import secure_filename


blueprint = Blueprint(
    'cernopendata',
    __name__,
    template_folder='templates',
    static_folder='static',
)

default_breadcrumb_root(blueprint, '.')

@blueprint.errorhandler(TemplateNotFound)
def template_not_found(err):
    """Log missing template."""
    current_app.logger.exception('Please check missing template.')
    abort(404)
    # return 'Template not found!', 404


def lazy_title(text, *args):
    """Make tranlated string with escaped values from request view args."""
    return _(text, **{key: make_lazy_string(
        lambda: escape(request.view_args.get(key, ''))
    ) for key in args})


@blueprint.route('/')
@register_menu(blueprint, 'main.education', _('Education'), order=2,
               active_when=lambda: False,
               endpoint_arguments_constructor=lambda: {'_anchor': 'education'})
@register_menu(blueprint, 'main.research', _('Research'), order=3,
               active_when=lambda: False,
               endpoint_arguments_constructor=lambda: {'_anchor': 'research'})
@register_breadcrumb(blueprint, '.', _('Home'))
@register_breadcrumb(blueprint, '.education', _('Education'),
                     endpoint_arguments_constructor=lambda: {
                         '_anchor': 'education'})
@register_breadcrumb(blueprint, '.research', _('Research'),
                     endpoint_arguments_constructor=lambda: {
                         '_anchor': 'education'})
def index():
    """Home Page."""
    return render_template('cernopendata/index.html')


@blueprint.route('/education')
@blueprint.route('/education/<string:experiment>')
@register_breadcrumb(blueprint, '.education.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def education(experiment=None):
    """Display education pages."""
    if experiment not in current_app.config['OPENDATA_EXPERIMENTS']:
        abort(404)

    return render_template('cernopendata/education.html',
                           experiment=experiment)



@blueprint.route('/research')
@blueprint.route('/research/<string:experiment>')
@register_breadcrumb(blueprint, '.research.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def research(experiment=None):
    import os.path, pkg_resources

    def file_exists(filename):
        filepath = pkg_resources.resource_filename('cernopendata.base', filename)
        return os.path.isfile(filepath)

    def splitting(value, delimiter='/'):
        return value.split(delimiter)

    current_app.jinja_env.filters['splitthem'] = splitting
    current_app.jinja_env.filters['file_exists'] = file_exists

    exp_colls, exp_names = get_collections()

    if experiment not in exp_names :
        return render_template('index_scrollspy.html', entry = 'research', exp_colls = exp_colls, exp_names = exp_names)

    return render_template('research.html',
                            experiment=experiment, exp_colls = exp_colls, exp_names = exp_names)


@blueprint.route('/visualise/events/<string:experiment>')
def visualise_events(experiment = 'CMS'):

    exp_names = get_collection_names(['ALICE', 'LHCb', 'ATLAS'])

    breadcrumbs = [{},{'url':'.education','text':'Education'},\
                        {'url':'.education','text':'Visualise Events'}]
    try:
        return render_template('visualise_events.html', experiment = experiment, exp_names = exp_names, breadcrumbs = breadcrumbs)
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/visualise/histograms/<string:experiment>')
def visualise_histo(experiment='CMS'):
    exp_colls, exp_names = get_collections()

    breadcrumbs = [{}, {'url':'.education','text':'Education'},
                        {'url':'.education','text':'Visualise Histograms'}]

    try:
        return render_template('visualise_histograms.html', experiment = experiment, exp_names = exp_names, breadcrumbs = breadcrumbs)
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/getting-started')
@register_breadcrumb(blueprint, '.get_started', _('Get Started'))
def get_started():
    """Render index of getting started tutorials."""
    return render_template('cernopendata/get_started/index.html')


@blueprint.route('/getting-started/<string:experiment>')
@blueprint.route('/getting-started/<string:experiment>/<string:year>')
@register_breadcrumb(blueprint, '.get_started.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def get_started_experiment(experiment=None, year=None):
    """Render getting started tutorials."""
    return render_template(
        'cernopendata/get_started/experiment_{0}.html'.format(
            experiment.lower()
        ), experiment=experiment, year=year,
    )


@blueprint.route('/resources')
@register_breadcrumb(blueprint, '.education.resources',
                     _('Learning Resources'))
def resources():
    """Render index of resources."""
    return render_template('cernopendata/resources.html')


@blueprint.route('/VM')
@blueprint.route('/VM/')
@register_breadcrumb(blueprint, '.vm', _('Virtual Machines'))
def vm():
    """Display experiment VMs."""
    return render_template('cernopendata/vm/index.html')


@blueprint.route('/VM/<string:experiment>', defaults={'year': None})
@blueprint.route('/VM/<string:experiment>/<string:year>')
@register_breadcrumb(blueprint, '.vm.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def vm_experiment(experiment, year):
    """Display details about experiment VMs."""
    return render_template(
        'cernopendata/vm/experiment_{0}.html'.format(experiment.lower()),
        year=year,
    )


@blueprint.route('/VM/<string:experiment>/validation/report')
@register_breadcrumb(blueprint, '.vm.validation_report',
                     lazy_title('%(experiment)s Validation Report',
                                'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def validation_report(experiment):
    """Display default abourt experiment validation report."""
    return render_template([
        'cernopendata/vm/validation_{0}.html'.format(experiment.lower()),
        'cernopendata/vm/validation.html',
    ], experiment=experiment)


def about_menu(*args):
    """Generate menu decorator."""
    def decorator(f):
        for order, key in enumerate(args):
            def arguments(key):
                return lambda: {'page': key}
            f = register_menu(
                blueprint, 'main.about.{0}'.format(key),
                _('%(experiment)s Open Data', experiment=key), order=order+1,
                endpoint_arguments_constructor=arguments(key)
            )(f)
        return f
    return decorator


def about_breadcrumbs():
    """Generate breadcrumbs for about pages."""
    key = request.view_args.get('page')
    breadcrumbs = [{'url': url_for('cernopendata.about'), 'text': _('About')}]
    if key:
        breadcrumbs.append({
            'url': url_for('cernopendata.about', experiment=key),
            'text': _('%(experiment)s Open Data', experiment=key),
        })
    return breadcrumbs


@blueprint.route('/about')
@blueprint.route('/about/<page>')
@register_menu(blueprint, 'main.about', _('About'), order=1)
@register_menu(blueprint, 'main.about.this', _('This Portal'), order=0)
@about_menu('CMS', 'ALICE', 'ATLAS', 'LHCb')
@register_breadcrumb(blueprint, '.about', _('About'),
                     dynamic_list_constructor=about_breadcrumbs)
def about(page='index'):
    """Render about page."""
    return render_template([
        'cernopendata/about/{0}.html'.format(
            secure_filename(page.lower()).replace('/', '-')
        ),
        'cernopendata/about/index.html',
    ])


@blueprint.route('/terms-of-use')
@register_breadcrumb(blueprint, '.terms', _('Terms of Use'))
def terms():
    """Render terms of use."""
    return render_template('cernopendata/terms_of_use.html')


@blueprint.route('/privacy-policy')
@register_breadcrumb(blueprint, '.privacy', _('Privacy Policy'))
def privacy():
    """Render privacy policy."""
    return render_template('cernopendata/privacy_policy.html')


@blueprint.route('/experiments')
def collections():
    import json, pkg_resources
    filepath = pkg_resources.resource_filename('cernopendata.base', 'templates/helpers/text/testimonials.json')
    with open(filepath,'r') as f:
        testimonials = json.load(f)

    def splitting(value, delimiter='/'):
        return value.split(delimiter)

    current_app.jinja_env.filters['splitthem'] = splitting

    exp_colls, exp_names = get_collections()

    return render_template('index_scrollspy.html', testimonials = testimonials, exp_colls = exp_colls, exp_names = exp_names)


@blueprint.route('/glossary', methods=['GET', 'POST'])
@register_menu(blueprint, 'main.about.glossary', _('Glossary'), order=90)

cernopendata/templates/cernopendata/education.html
{%- extends config.BASE_TEMPLATE %}

{% block page_body %}

<section class="entrypoint_collections">
  <div class="tab-content">
    <div class="tab-pane fade {%  if exp not in exp_names %}in active{% endif%}" id="general">
      <section class="subcollection_desc experiments">
        <div class="container">
          <p class="lead">
            For education purposes, the complex primary data need to be
            processed into a format (examples below) that is good for simple
            applications. Get in touch if you wish to build your own
            applications similar to those shown here.
          </p>
          <ul class="row">
          {% set coll_portalboxes = {'desc': 'Description goes here..', 'image': 'default.png'} %}
          {% for cols in exp_colls %}
            {% for pb in cols.portalboxes %}
              {% if (pb.portalbox.title == 'description') %}
                {% if coll_portalboxes.update({'desc': pb.portalbox.body}) %}{% endif %}
              {% elif (pb.portalbox.title == 'image') %}
                {% if coll_portalboxes.update({'image': pb.portalbox.body}) %}{% endif %}
              {% endif %}
            {% endfor %}
            <li class="col-xs-12">
              <div class="subcollection_exp">
              {#
                <a href="{{ url_for((request.path|splitthem)[1]+'/'+cols['name']) }}"><div class="coll-thumb col-xs-2">
                  <img class="center-block" src="{{ url_for('static', filename='img/'+coll_portalboxes['image']) }}" alt="">
                </div></a>
                <div class="coll-desc col-xs-10">
                  {{ coll_portalboxes['desc']|replace('#$#$#','')|safe }}
                </div>
                <div class="coll-button">
                    <a href="{{url_for('.education', exp = cols.name)}}" class="btn">Explore {{cols.name_ln}} <span class="fa fa-chevron-right"></span></a>
                </div>
              #}
              </div>
            </li>
          {% endfor %}
          </ul>
        </div>
      </section>
      <section class="learn">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <img src="{{ url_for('static', filename='img/edu_img_1.png') }}" alt="" class="img-responsive img-circle center-block">
            </div>
            <div class="col-md-4">
              <img src="{{ url_for('static', filename='img/edu_img_2.jpg') }}" alt="" class="img-responsive img-circle center-block">
            </div>
            <div class="col-md-4">
              <img src="{{ url_for('static', filename='img/edu_img_3.png') }}" alt="" class="img-responsive img-circle center-block">
            </div>
          </div>
        </div>
        <div class="_slogan container">
          <!-- Info text can go here -->
        </div>
      </section>
    </div>
    
    {#
    {% import 'search/collections/CMS_education_apps.html' as b with context %}
    #}
    {% for e in config.OPENDATA_EXPERIMENTS %}
    <div class="tab-pane fade {%  if experiment == e %}in active{% endif%}" id="{{e}}">
      <section class="subcollection_apps subcollection_desc">
        <div class="container">
          <div class="row">
          {{ e }}
          {#
          {% if ('templates/search/collections/'+e.name+'_education_apps.html')|file_exists %}
          <div class="col-sm-12 col-md-6">
            <div class="row">
              {% set coll_portalboxes = {'desc': 'Description goes here..', 'image': 'default.png'} %}
              {% for pb in e.portalboxes %}
              {% if (pb.portalbox.title == 'description') %}
              {% if coll_portalboxes.update({'desc': pb.portalbox.body}) %}{% endif %}
              {% elif (pb.portalbox.title == 'image') %}
              {% if coll_portalboxes.update({'image': pb.portalbox.body}) %}{% endif %}
              {% endif %}
              {% endfor %}
              <div class="coll-desc">
                {{ coll_portalboxes['desc']|replace('#$#$#', '')|safe }}
              </div>
            </div>
          </div>  
          <div class="col-sm-12 col-md-6">{% include ('search/collections/'+e.name+'_education_apps.html') ignore missing %}</div>
          {% else %}
          <div class="col-md-12">
            <div class="row">
              {% set coll_portalboxes = {'desc': 'Description goes here..', 'image': 'default.png'} %}
              {% for pb in e.portalboxes %}
              {% if (pb.portalbox.title == 'description') %}
              {% if coll_portalboxes.update({'desc': pb.portalbox.body}) %}{% endif %}
              {% elif (pb.portalbox.title == 'image') %}
              {% if coll_portalboxes.update({'image': pb.portalbox.body}) %}{% endif %}
              {% endif %}
              {% endfor %}
              <div class="coll-desc">
                {{ coll_portalboxes['desc']|replace('#$#$#', '')|safe }}
              </div>
            </div>
          </div>
          {% endif %}
          #}
          </div> 
        </div>
      </section>
      {% with exp_collection = e %}
        {# include "helpers/collections_educate.html" #}
      {% endwith %}
    </div>      
    {% endfor %}
  </div>

</section>
{% endblock page_body %}

{%- block javascript %}
{{super()}}
<script>
$(document).ready(function() {
  // add a hash to the URL when the user clicks on a tab
  $('a[data-toggle="tab"]').on('click', function(e) {
    history.pushState(null, null, $(this).attr('href'));
  });
  // navigate to a tab when the history changes
  window.addEventListener("popstate", function(e) {
    var activeTab = $('[href="' + location.pathname + '"][data-toggle="tab"]');
    if (activeTab.length) {
      activeTab.tab('show');
    } else {
      $('.nav-tabs a:first').tab('show');
    }
  });
});
</script>
{% endblock %}

cernopendata/templates/cernopendata/footer.html
<footer id="footer">
  <hr/>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <a href="http://www.cern.ch">
          <img src="{{ url_for('static', filename='img/opendata/cern-logo-large.png') }}" alt="CERN">
        </a>
      </div>
      <div class="text-right col-md-6">
        <a href="http://alice.cern.ch">
          <img src="{{ url_for('static', filename='img/ALICE.gif') }}" alt="ALICE">
        </a>
        <a href="http://atlas.ch">
          <img src="{{ url_for('static', filename='img/ATLAS.svg') }}" alt="ATLAS">
        </a>
        <a href="http://cms.cern.ch">
          <img src="{{ url_for('static', filename='img/CMS.gif') }}" alt="CMS">
        </a>
        <a href="http://lhcb.cern.ch">
          <img src="{{ url_for('static', filename='img/LHCb.gif') }}" alt="LHCb">
        </a>
      </div>
    </div>
    <br/>
    <div class="row small">
      <div class="text-center col-md-push-3 col-md-6">
        <ul class="list-inline" style="display: inline;">
          <li>© 2014, 2015, 2016 CERN</li>
          <li><a href="{{ url_for('cernopendata.terms') }}">Terms of Use</a></li>
          <li><a href="{{ url_for('cernopendata.privacy') }}">Privacy Policy</a></li>
          <li><a href="mailto:opendata-support@cern.ch">Contact</a></li>
        </ul>
      </div>
      <div class="col-md-pull-6 col-md-3 col-xs-6">
        {% trans link="http://inveniosoftware.org" %}Powered by <a href="{{link}}">Invenio</a>{% endtrans %}
      </div>
      <div class="text-right col-md-3 col-xs-6">
        {% if config.I18N_LANGUAGES %}
          {% from "invenio_i18n/macros/language_selector.html" import language_selector %}
          {{ language_selector() }}
        {% endif %}
      </div>
    </div>
    <br/>
  </div>
</footer>

cernopendata/templates/cernopendata/glossary.html
{%- extends config.BASE_TEMPLATE %}

{%- block page_body %}
<section id="glossary" class="general content">
  <div class="container">
    <div class="row">
      <div class="page-header">
        <h2>Glossary Terms</h1>
      </div>
      {% for i in glossary %}
        {% if i.status != "WIP" %}
        <div>
          <h3 id="{{ i.anchor }}">
            <a href="#{{ i.anchor }}">
              <i class="fa fa-anchor pull-right"></i>
              {%- if i.term is string %}
                {{- i.term }}
              {%- else %}
                {{- i.term[0]}}
              {%- endif %}
            </a>
            {% if i.see_also %}
            <br/>
            <small>
              <em>see also:
              {% for s in i.see_also %}
                <a href="#{{s.term}}">{{ s.term }}</a>{{', ' if not loop.last}}
              {% endfor %}
              </em>
            </small>
            {% endif %}
          </h3>
        </div>
        <p>
          {{ i.definition }}
        </p>
        <p>
          {% for e in i.experiment %}
            <a class="label label-primary" href="#">{{e.name}}</a>
          {% endfor %}
        </p>
        {% if i.links %}
        <p>
          {% for l in i.links %}
          <a href="{{l.url}}">{{l.text}}</a>
          {% endfor %}
        </p>
        {% endif %}
        {% if not loop.last %}
          <hr/>
        {% endif %}
        {% endif %}
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

cernopendata/templates/cernopendata/header.html
{%- extends "invenio_theme/header.html" %}

{%- block breadcrumbs %}
{% if request.path != '/' and breadcrumbs|length > 1 %}
<section class="bg-info pull-row-up">
  {{ super() }}
</section>
{% endif %}
{%- endblock %}

cernopendata/templates/cernopendata/index.html
{%- extends config.BASE_TEMPLATE %}

{% macro experiment_panel(name, description, endpoint) %}
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="col-md-2">
        <a href="{{ url_for(endpoint, experiment=name) }}">
          <img src="{{ url_for('static', filename='img/' + name + '.gif') }}"
                alt="{{ name }}" style="width: 100%;">
        </a>
      </div>
      <div class="col-md-10">
        {{ description|safe }}
      </div>
    </div>
    <div class="panel-footer text-right">
        <a href="{{ url_for(endpoint, experiment=name) }}"
            class="btn btn-sm btn-default">
          {{ _('Explore %(name)s', name=name) }}
          <i class="fa fa-chevron-right"></i>
        </a>
    </div>
  </div>
{% endmacro %}

{% macro img_panel(url, src, text) %}
<div class="panel panel-default">
  <a href="{{ url }}">
    <div style="background-image: url({{ src }}); background-position: center; background-size: 100% 100%; background-repeat: no-repeat; height: 24vh; width: 100%;"></div>
  </a>
  <div class="panel-footer">
    <a href="{{ url }}" class="btn btn-default btn-block">
      {{ text }} <i class="fa fa-chevron-right"></i>
    </a>
  </div>
</div>
{% endmacro %}

{%- block page_body %}
  <section id="main" class="homepage-frame">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div id="edu" class="panel panel-default">
            <div class="panel-body">
              <h2>{{ _('Education') }}</h2>
              <hr/>
              <p class="lead">
                {{ _('Visualise events, check reconstructed data, run tools or build your own!') }}
              </p>
            </div>
            <div class="panel-footer">
              <a class="btn btn-primary btn-lg btn-block" href="#education">{{ _('Start learning') }}</a>
            </div>
          </div>
        </div>

        <div class="col-md-4 col-md-offset-4">
          <div id="rsch" class="panel panel-default">
            <div class="panel-body">
              <h2>{{ _('Research') }}</h2>
              <hr/>
              <p class="lead">
                {{ _('Get the genuine working environments, virtual machines and datasets to start your research.') }}
              </p>
            </div>
            <div class="panel-footer">
              <a class="btn btn-info btn-lg btn-block" href="#research">{{ _('Start analysing') }}</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="education" class="homepage-frame">
    <div class="entry-frame-header">
      <h1><div class="container">Education</div></h1>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-xs-12">
          {% for name, description, show_link in config.OPENDATA_EDUCATION %}
            {{ experiment_panel(name, description, '.education') }}
          {% endfor %}
        </div>
        <div class="col-sm-6 col-xs-12">
          <p>
            {{ _('For education purposes, the complex primary data need to be processed into a format (examples below) that is good for simple applications.Get in touch if you wish to build your own applications similar to those shown here.') }}
          </p>
          <div class="row">
            <div class="col-md-6">
              {{ img_panel(
                url_for('.visualise_events', experiment='CMS'),
                url_for('static', filename='img/home/event.png'),
                _('Visualise events')
              ) }}
            </div>
            <div class="col-md-6">
              {{ img_panel(
                url_for('.visualise_histo', experiment='CMS'),
                url_for('static', filename='img/home/histo.png'),
                _('Visualise histograms')
              ) }}
            </div>
            <div class="col-md-12">
              {{ img_panel(
                url_for('.resources'),
                url_for('static', filename='img/CMSMasterclass.jpg'),
                _('Learning Resources')
              ) }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="research" class="homepage-frame">
    <div class="entry-frame-header">
      <h1><div class="container">{{ _('Research') }}</div></h1>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-xs-12">
          {% for name, description, show_link in config.OPENDATA_EDUCATION %}
            {{ experiment_panel(name, description, '.research') }}
          {% endfor %}
        </div>
        <div class="col-sm-6 col-xs-12">
          <p>
            {{ _('For research purposes, specific software environments and tools need to be deployed to analyse these complex primary data. In addition to the data below, you will find instructions for setting up your working environments here.') }}
          </p>
          <div class="row">
            <div class="col-md-12">
              {{ img_panel(
                url_for('.vm'),
                url_for('static', filename='img/home/VMs.jpg'),
                _('Install your Virtual Machine')
              ) }}
            </div>
            <div class="col-md-12">
              {{ img_panel(
                url_for('.get_started'),
                url_for('static', filename='img/default.png'),
                _('Start analysing the data')
              ) }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{%- endblock %}

cernopendata/templates/cernopendata/page.html
{% extends 'invenio_theme/page.html' %}

{% block css %}
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,500,700,400italic" rel="stylesheet">
    {%- assets "cernopendata_theme_css" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
    {%- endassets %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{%- endblock css %}

{%- block page_header %}
{% include 'cernopendata/header.html' %}
{%- endblock page_header %}

{%- block page_footer %}
{% include "cernopendata/footer.html" %}
{%- endblock page_footer %}

cernopendata/templates/cernopendata/privacy_policy.html
{%- extends config.BASE_TEMPLATE %}

{%- block page_body %}
<section id="termsofuse" class="content">
  <div class="container">
    <div class="row">
      <div class="page-header">
        <h2>{{ _('CERN Open Data Privacy Policy') }}</h3>
      </div>

      <p>CERN does not track, collect or retain personal information from users of CERN Open Data Portal, except as otherwise provided herein. In order to enhance CERN Open Data Portal and monitor traffic, non-personal information such as IP addresses and cookies may be tracked and retained, as well as log files shared in aggregation with other community services. User provided information, like corrections of metadata or paper claims, will be integrated into the database without displaying its source and may shared with other services.</p>
      <p>CERN Open Data Portal will take all reasonable measures to protect the privacy of its users and to resist service interruptions, intentional attacks, or other events that may compromise the security of the CERN Open Data Portal website.</p>
      <p>If you have any questions about the CERN Open Data Portal privacy policy, please contact <a href="mailto:opendata-support@cern.ch">opendata-support@cern.ch</a></p>

    </div>
  </div>
</section>

{% endblock %}

cernopendata/templates/cernopendata/resources.html
{%- extends config.BASE_TEMPLATE %}

{%- block page_body %}
<section class="general">
  <div class="container">
    <p class="lead">
      The collections below list resources for teaching and learning about
      particle physics, built using CERN Open Data. Please note that these are
      external resources: they are not hosted on the CERN Open Data portal.
    </p>
    <div class="row">
      {% for e in config.OPENDATA_EXPERIMENTS %}
      <div class="col-md-6">
        <div class="panel panel-default">
          <a href="{{ url_for('invenio_collections.collection',
                              name=e+"-Learning-Resources" ) }}">
            <div class="panel-body">
                <img src="{{ url_for('static', filename='img/'+e+'.gif') }}" alt=""
                    class="img-cirle center-block" style="height: 15vh;">
            </div>
            <div class="panel-footer">
              <h3 class="text-center">
                {{ _('%(experiment)s Learning Resources', experiment=e) }}
              </h3>
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}

cernopendata/templates/cernopendata/search.html
{% extends "invenio_search_ui/search.html" %}

{# FIXME
{%- block javascript %}
{% assets "cernopendata_theme_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}
#}

{%- block search_results %}
<invenio-search-results
 template="{{ url_for('static', filename='templates/cernopendata_search_ui/results.html') }}">
</invenio-search-results>
{%- endblock search_results %}

{# FIXME
{%- block search_facets %}
<div class="col-md-3 col-md-pull-9 col-xs-12">
  <invenio-search-facets
   template="{{ url_for('static', filename='templates/cernopendata_search_ui/facets.html') }}">
  </invenio-search-facets>
</div>
{%- endblock search_facets %}
#}

cernopendata/templates/cernopendata/terms_of_use.html
{%- extends config.BASE_TEMPLATE %}

{%- block page_body %}
<section id="termsofuse" class="content">
  <div class="container">
    <div class="row">
      <div class="page-header">
        <h2>{{ _('CERN Open Data Terms of Use') }}</h2>
      </div>
      <p class="lead">
        The CERN Open Data Portal is offered by CERN as part of its mission to
        publish the results of its experimental and theoretical work.
      </p>
      <p>
        Use of the CERN Open Data Portal service denotes agreement with the
        following terms:

        <ol>
          <li>The CERN Open Data Portal is provided free of charge.</li>
          <li>All metadata and datasets in the CERN Open Data Portal are made available under the terms of the CC0 waiver.</li>
          <li>All other content is made available under its applicable license conditions as specified on the relevant web pages. For example, software packages are usually licensed under GNU General Public License (GPL). Download and use of such other content from the CERN Open Data Portal does not, unless expressly stated in the applicable license conditions, transfer any intellectual property. Bulk downloading of email addresses taken from CERN Open Data Portal is not allowed.</li>
          <li>All content is provided “as is” and the user shall hold CERN and the content providers free and harmless in connection with its use of such content.</li>
          <li>CERN reserves the right, without notice, at its sole discretion and without liability, to restrict or remove user access where it considers that use of the CERN Open Data Portal interferes with its operations or violates these Terms of Use or applicable laws.</li>
          <li>These terms of Use are subject to change by CERN at any time and without notice, other than through posting the updated Terms of Use on the CERN Open Data Portal website.</li>
        </ol>

        If you have any questions or comments with respect to the CERN Open
        Data Portal, or if you are unsure whether your intended use is in line
        with these Terms of Use, or if you seek permission for a use that does
        not fall within these Terms of Use, please contact <a
        href="mailto:opendata-support@cern.ch">opendata-support@cern.ch</a>.
      </p>
    </div>
  </div>
</section>
{%- endblock %}