cernopendata/views.py
# -*- coding: utf-8 -*-

"""cernopendata base Invenio configuration."""

from __future__ import absolute_import, print_function

import functools
import json
import pkg_resources

from flask import Blueprint, abort, current_app, escape, render_template, request, url_for
from flask_babelex import lazy_gettext as _
from flask_breadcrumbs import default_breadcrumb_root, register_breadcrumb
from flask_menu import register_menu
from jinja2.exceptions import TemplateNotFound
from speaklater import make_lazy_string
from werkzeug import secure_filename


blueprint = Blueprint(
    'cernopendata',
    __name__,
    template_folder='templates',
    static_folder='static',
)

default_breadcrumb_root(blueprint, '.')

@blueprint.errorhandler(TemplateNotFound)
def template_not_found(err):
    """Log missing template."""
    current_app.logger.exception('Please check missing template.')
    abort(404)
    # return 'Template not found!', 404


def lazy_title(text, *args):
    """Make tranlated string with escaped values from request view args."""
    return _(text, **{key: make_lazy_string(
        lambda: escape(request.view_args.get(key, ''))
    ) for key in args})


@blueprint.route('/')
@register_menu(blueprint, 'main.education', _('Education'), order=2,
               active_when=lambda: False,
               endpoint_arguments_constructor=lambda: {'_anchor': 'education'})
@register_menu(blueprint, 'main.research', _('Research'), order=3,
               active_when=lambda: False,
               endpoint_arguments_constructor=lambda: {'_anchor': 'research'})
@register_breadcrumb(blueprint, '.', _('Home'))
@register_breadcrumb(blueprint, '.education', _('Education'),
                     endpoint_arguments_constructor=lambda: {
                         '_anchor': 'education'})
@register_breadcrumb(blueprint, '.research', _('Research'),
                     endpoint_arguments_constructor=lambda: {
                         '_anchor': 'education'})
def index():
    """Home Page."""
    return render_template('cernopendata/index.html')


@blueprint.route('/education')
@blueprint.route('/education/<string:experiment>')
@register_breadcrumb(blueprint, '.education.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def education(experiment=None):
    """Display education pages."""
    if experiment not in current_app.config['OPENDATA_EXPERIMENTS']:
        abort(404)

    return render_template('cernopendata/education.html',
                           experiment=experiment)



@blueprint.route('/research')
@blueprint.route('/research/<string:experiment>')
@register_breadcrumb(blueprint, '.research.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def research(experiment=None):
    import os.path, pkg_resources

    def file_exists(filename):
        filepath = pkg_resources.resource_filename('cernopendata.base', filename)
        return os.path.isfile(filepath)

    def splitting(value, delimiter='/'):
        return value.split(delimiter)

    current_app.jinja_env.filters['splitthem'] = splitting
    current_app.jinja_env.filters['file_exists'] = file_exists

    exp_colls, exp_names = get_collections()

    if experiment not in exp_names :
        return render_template('index_scrollspy.html', entry = 'research', exp_colls = exp_colls, exp_names = exp_names)

    return render_template('research.html',
                            experiment=experiment, exp_colls = exp_colls, exp_names = exp_names)


@blueprint.route('/visualise/events/<string:experiment>')
def visualise_events(experiment = 'CMS'):

    exp_names = get_collection_names(['ALICE', 'LHCb', 'ATLAS'])

    breadcrumbs = [{},{'url':'.education','text':'Education'},\
                        {'url':'.education','text':'Visualise Events'}]
    try:
        return render_template('visualise_events.html', experiment = experiment, exp_names = exp_names, breadcrumbs = breadcrumbs)
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/visualise/histograms/<string:experiment>')
def visualise_histo(experiment='CMS'):
    exp_colls, exp_names = get_collections()

    breadcrumbs = [{}, {'url':'.education','text':'Education'},
                        {'url':'.education','text':'Visualise Histograms'}]

    try:
        return render_template('visualise_histograms.html', experiment = experiment, exp_names = exp_names, breadcrumbs = breadcrumbs)
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/getting-started')
@register_breadcrumb(blueprint, '.get_started', _('Get Started'))
def get_started():
    """Render index of getting started tutorials."""
    return render_template('cernopendata/get_started/index.html')


@blueprint.route('/getting-started/<string:experiment>')
@blueprint.route('/getting-started/<string:experiment>/<string:year>')
@register_breadcrumb(blueprint, '.get_started.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def get_started_experiment(experiment=None, year=None):
    """Render getting started tutorials."""
    return render_template(
        'cernopendata/get_started/experiment_{0}.html'.format(
            experiment.lower()
        ), experiment=experiment, year=year,
    )


@blueprint.route('/resources')
@register_breadcrumb(blueprint, '.education.resources',
                     _('Learning Resources'))
def resources():
    """Render index of resources."""
    return render_template('cernopendata/resources.html')


@blueprint.route('/VM')
@blueprint.route('/VM/')
@register_breadcrumb(blueprint, '.vm', _('Virtual Machines'))
def vm():
    """Display experiment VMs."""
    return render_template('cernopendata/vm/index.html')


@blueprint.route('/VM/<string:experiment>', defaults={'year': None})
@blueprint.route('/VM/<string:experiment>/<string:year>')
@register_breadcrumb(blueprint, '.vm.experiment',
                     lazy_title('%(experiment)s', 'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def vm_experiment(experiment, year):
    """Display details about experiment VMs."""
    return render_template(
        'cernopendata/vm/experiment_{0}.html'.format(experiment.lower()),
        year=year,
    )


@blueprint.route('/VM/<string:experiment>/validation/report')
@register_breadcrumb(blueprint, '.vm.validation_report',
                     lazy_title('%(experiment)s Validation Report',
                                'experiment'),
                     endpoint_arguments_constructor=lambda: {
                         'experiment': request.view_args['experiment']})
def validation_report(experiment):
    """Display default abourt experiment validation report."""
    return render_template([
        'cernopendata/vm/validation_{0}.html'.format(experiment.lower()),
        'cernopendata/vm/validation.html',
    ], experiment=experiment)


def about_menu(*args):
    """Generate menu decorator."""
    def decorator(f):
        for order, key in enumerate(args):
            def arguments(key):
                return lambda: {'page': key}
            f = register_menu(
                blueprint, 'main.about.{0}'.format(key),
                _('%(experiment)s Open Data', experiment=key), order=order+1,
                endpoint_arguments_constructor=arguments(key)
            )(f)
        return f
    return decorator


def about_breadcrumbs():
    """Generate breadcrumbs for about pages."""
    key = request.view_args.get('page')
    breadcrumbs = [{'url': url_for('cernopendata.about'), 'text': _('About')}]
    if key:
        breadcrumbs.append({
            'url': url_for('cernopendata.about', experiment=key),
            'text': _('%(experiment)s Open Data', experiment=key),
        })
    return breadcrumbs


@blueprint.route('/about')
@blueprint.route('/about/<page>')
@register_menu(blueprint, 'main.about', _('About'), order=1)
@register_menu(blueprint, 'main.about.this', _('This Portal'), order=0)
@about_menu('CMS', 'ALICE', 'ATLAS', 'LHCb')
@register_breadcrumb(blueprint, '.about', _('About'),
                     dynamic_list_constructor=about_breadcrumbs)
def about(page='index'):
    """Render about page."""
    return render_template([
        'cernopendata/about/{0}.html'.format(
            secure_filename(page.lower()).replace('/', '-')
        ),
        'cernopendata/about/index.html',
    ])


@blueprint.route('/terms-of-use')
@register_breadcrumb(blueprint, '.terms', _('Terms of Use'))
def terms():
    """Render terms of use."""
    return render_template('cernopendata/terms_of_use.html')


@blueprint.route('/privacy-policy')
@register_breadcrumb(blueprint, '.privacy', _('Privacy Policy'))
def privacy():
    """Render privacy policy."""
    return render_template('cernopendata/privacy_policy.html')


@blueprint.route('/experiments')
def collections():
    import json, pkg_resources
    filepath = pkg_resources.resource_filename('cernopendata.base', 'templates/helpers/text/testimonials.json')
    with open(filepath,'r') as f:
        testimonials = json.load(f)

    def splitting(value, delimiter='/'):
        return value.split(delimiter)

    current_app.jinja_env.filters['splitthem'] = splitting

    exp_colls, exp_names = get_collections()

    return render_template('index_scrollspy.html', testimonials = testimonials, exp_colls = exp_colls, exp_names = exp_names)


@blueprint.route('/glossary', methods=['GET', 'POST'])
@register_menu(blueprint, 'main.about.glossary', _('Glossary'), order=90)

cernopendata/templates/cernopendata/VM/detail.html
{%- extends config.BASE_TEMPLATE %}

{%- block page_body %}
<div class="container">
  {%- block vm_detail %}
    {%- set year = year|default(years[-1], True) %}
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      {% for y in years %}
      <li role="presentation" class="{{ 'active' if y == year -}}">
        <a href="#year{{ y }}" aria-controls="settings" role="tab" data-toggle="tab">
          {{ y }}
        </a>
      </li>
      {% endfor %}
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      {%- for y in years %}
      <div role="tabpanel" class="tab-pane fade{{ ' in active' if y == year }}"
          id="year{{ y }}">
        {% include 'cernopendata/vm/experiment_%(e)s_%(y)s.html'|format(
          e=request.view_args['experiment']|lower, y=y
        ) %}
      </div>
      {%- endfor %}
    </div>
  {%- endblock %}
</div>
{% endblock %}

cernopendata/templates/cernopendata/VM/experiment_alice.html
{%- extends 'cernopendata/VM/detail.html' %}

{% block vm_detail %}
<div class="row">
  <div class="about">
    <h1 class="col-sm-12">ALICE Virtual Machines: How to install</h1>
  </div>
  <div class="col-sm-12">
    <ol class="gen-menu">
      <li><a href="#vbox">How to install VirtualBox</a></li>
      <li><a href="#create">Create a VM</a></li>
      <li><a href="#configure">Configure a VM</a></li>
    </ol>
  </div>


  <div class="col-sm-12">
    <div class="gen-box">
      <h2  id="vbox">Step 1: Installing VirtualBox</h2>
      <p>VirtualBox is a free, open source and multiplatform application to run virtual machines: you can <a href="https://www.VirtualBox.org/wiki/Downloads">download</a> the package for your platform from the Downloads page.</p>
      <p>You will need administrative privileges ("root" privileges) on every platform to perform the installation of VirtualBox.</p>
      <p>Note: the latest tested version of VirtualBox working with CernVM is 4.3.14. If you have troubles with the latest verion of VirtualBox, pick that one: the full history of VirtualBox versions is available <a href="https://www.VirtualBox.org/wiki/Download_Old_Builds">on a different page.</a></p>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="gen-box">
      <h2 id="create">Step 2: Creating a Virtual Machine</h2>
      <div class="row">
        <p class="col-md-8">Go on the <a href="http://cernvm.cern.ch/portal/downloads">CernVM downloads page</a> and download the appropriate version: you must pick the OVA x86_64 for VirtualBox.</p>
        <div class="col-md-4"><img src="{{url_for('static', filename='img/alice/1.png')}}" width="100%;"></div>
        <p class="col-md-12">Now open VirtualBox. Select <b>Import Appliance</b>... from the <b>File</b> menu.</p>
        <div class="col-md-12">
          <img src="{{url_for('static', filename='img/alice/2.png')}}" alt="">
        </div>
        <p class="col-md-12">
          From the import dialog, select the OVA file you have just downloaded.
        </p>
        <div class="col-md-12"><img src="{{ url_for('static', filename='img/alice/3.png')}}" alt=""></div>
        <p class="col-md-12">
          In the Appliance settings dialog, change the following values:<br/><br/>
          * change the name to whatever you want in order to recognise your VM in the future</br>
          * increase the RAM to 2048 MB</br>
          * check "Reinitialize the MAC address of all network cards"</br>
          You can compare your settings with the picture below.
        </p>
        <div class="col-md-12">
          <img src="{{ url_for('static', filename='img/alice/4.png')}}" alt="">
        </div>
        <p class="col-md-12">Click <b>Import</b>. You will have now the CernVM virtual machine available in the list of virtual machines. Select it, then press the <b>Start</b> button to boot it.</p>
        <div class="col-md-12">
          <img src="{{url_for('static', filename='img/alice/5.png')}}" alt="">
        </div>
        <p class="col-md-12">Let CernVM finish the boot process. As you might have noticed, the OVA file you have downloaded is less than 20 MB in size: in fact, it does not contain the operating system's components, which are downloaded on demand as soon as you access them.</p>
        <p class="col-md-12">For this reason, the first boot might take longer. Afterwards, the main components will be accessed from the cache.</p>
        <p class="col-md-12">Note: CernVM needs Internet connectivity to run. You cannot run CernVM when you are offline.</p>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="gen-box">
      <h2 id="configure">Step 3: Configuring a Virtual Machine</h2>
      <p>When the virtual machine is started, it is a generic virtual machine, not configured to any specific purpose. It does not even have users, thus you still cannot log in: you have to specialise it by applying a configuration.</p>

      <p>This process is called contextualisation, and can be performed entirely using a web browser: just start by navigating to the CernVM Online web site.</p>

      <p>The first time you connect you need to register: the procedure takes seconds. Click on the register link:</p>
      <div class="col-md-12"><img src="{{ url_for('static', filename='img/alice/6.png')}}" alt=""></div>
      <p>Complete the registration form. You must provide a valid email address: you will receive a confirmation email for activating the account.</p>
      <div class="col-md-12"><img src="{{ url_for('static', filename='img/alice/7.png')}}" alt=""></div>
      <p><b>Note:</b> please make sure that the "captcha" is filled correctly.</p>
      <p>Once you have registered, you can go back to the login page and provide your credentials.</p>
      <p>In this example, we are looking for the <b>ALICE analysis</b> configuration for the <b>ALICE</b> experiment: adapt the example to the configuration you wish to apply.</p>
      <p>From the top menu, click on <b>Marketplace (Step A)</b>, then on the bottom right click on <b>ALICE (Step B)</b>. From the list of available configurations, select <b>ALICE analysis (Step C)</b> as shown in the picture.</p>
      <div class="col-md-12"><img src="{{ url_for('static', filename='img/alice/8.png')}}" alt=""></div>

      <p>When the configuration is selected, click the <b>Pair button (Step D)</b>: a six-digit number will appear on the screen, as shown in the picture:</p>
      <div class="col-md-12"><img src="{{ url_for('static', filename='img/alice/9.png')}}" alt=""></div>
      <p>Don't close this web page. Go instead to VirtualBox, where you have the login screen of CernVM. At the login screen, type the pound sign (#) followed by the six digits (no spaces).</p>
      <div class="col-md-12"><img src="{{ url_for('static', filename='img/alice/10.png')}}" alt=""></div>

      <p>The virtual machine will download the configuration automatically, and the web page on CernVM Online will update automatically.</p>
      <div class="col-md-12"><img src="{{ url_for('static', filename='img/alice/11.png')}}" alt=""></div>


      <p>Your CernVM virtual machine should now present a graphical interface: you can start using it immediately. Enjoy!</p>
    </div>
  </div>
</div>
{% endblock %}

cernopendata/templates/cernopendata/VM/experiment_cms.html
{%- extends 'cernopendata/VM/detail.html' %}
{%- set years = ['2010', '2011'] %}

cernopendata/templates/cernopendata/VM/experiment_cms_2010.html
{% import 'helpers/text/vms_page_2010.html' as text %}

<div class="row">
  <div class="about">
    <h1>{{ text.about_cms_msg('/getting-started/CMS') }}</h1>
  </div>
  <div class="col-md-12">
    <ol class="gen-menu">
      <li>
        <a href="#install2010">How to install a CERN VM</a>
      </li>
      <li>
        <a href="#issues2010">Issues  &amp; Limitations</a>
      </li>
      <li>
        <a href="#testvalidate2010">How to Test  &amp; Validate?</a>
      </li>
    </ol>
  </div>
  <h1 id="install2010" class="col-sm-12">How to install a CERN Virtual Machine</h1>
  <div class="col-sm-12">
    <div class="gen-box">{{ text.cms_install_2010_s1() }}</div>
  </div>
  <div class="col-sm-12">
    <div class="gen-box">{{ text.cms_install_2010_s2('/record/250') }}</div>
  </div>

  <h1 id="testvalidate2010" class="col-sm-12">How to Test  &amp; Validate?</h1>
  <div class="col-sm-12">
    <div class="gen-box">
      {{ text.cms_validate_intro_2010('/getting-started/CMS') }}
    </div>
  </div>
  <div class="col-sm-12">
    <div class="gen-box">
      {{ text.cms_validate_2010_s1() }}
    </div>
  </div>

  <h1 id="issues2010" class="col-sm-12">Known Issues  &amp; Limitations</h1>
  <div class="col-sm-12">
    <div class="gen-box">
      {{ text.cms_validate_2010_s2('/VM/CMS/validation/report') }}
    </div>
  </div>
  <div class="col-sm-12">
    <div class="gen-box">
      {{ text.cms_limitation_2010_s1() }}
    </div>
  </div>
</div>

cernopendata/templates/cernopendata/VM/experiment_cms_2011.html
{% import 'helpers/text/vms_page_2011.html' as text %}

<div class="row">
  <div class="about">
    <h1>{{ text.about_cms_msg('/getting-started/CMS') }}</h1>
  </div>
  <div class="col-md-12">
    <ol class="gen-menu">
      <li>
        <a href="#install2011">How to install a CERN VM</a>
      </li>
      <li>
        <a href="#issues2011">Issues  &amp; Limitations</a>
      </li>
      <li>
        <a href="#testvalidate2011">How to Test  &amp; Validate?</a>
      </li>
    </ol>
  </div>
  <h1 id="install2011" class="col-sm-12">How to install a CERN Virtual Machine</h1>
  <div class="col-sm-12">
    <div class="gen-box">{{ text.cms_install_2011_s1() }}</div>
  </div>
  <div class="col-sm-12">
    <div class="gen-box">{{ text.cms_install_2011_s2('/record/252') }}</div>
  </div>

  <h1 id="testvalidate2011" class="col-sm-12">How to Test  &amp; Validate?</h1>
  <div class="col-sm-12">
    <div class="gen-box">
      {{ text.cms_validate_intro_2011('/getting-started/CMS') }}
    </div>
  </div>
  <div class="col-sm-12">
    <div class="gen-box">
      {{ text.cms_validate_2011_s1() }}
    </div>
  </div>

  <h1 id="issues2011" class="col-sm-12">Known Issues  &amp; Limitations</h1>
  <div class="col-sm-12">
    <div class="gen-box">
      {{ text.cms_validate_2011_s2('/VM/CMS/validation/report') }}
    </div>
  </div>
  <div class="col-sm-12">
    <div class="gen-box">
      {{ text.cms_limitation_2011_s1() }}
    </div>
  </div>
</div>

cernopendata/templates/cernopendata/VM/experiment_lhcb.html
{%- extends 'cernopendata/VM/detail.html' %}

{% block vm_detail %}
<div class="row">
  <div class="about">
    <h1 class="col-sm-12">LHCb Virtual Machines: How to install</h1>
  </div>
  <div class="col-sm-12">
    <ol class="gen-menu">
      <li><a href="#vbox">How to install VirtualBox</a></li>
      <li><a href="#download">Download a LHCb virtual machine and run!</a></li>
    </ol>
  </div>

  <div class="col-sm-12">
    <div class="gen-box">
      <h2 id="vbox">Step 1: Installing VirtualBox</h2>
      <p>VirtualBox is a free, open source and multiplatform application to run virtual machines: you can <a href="https://www.VirtualBox.org/wiki/Downloads">download</a> the package for your platform from the Downloads page.</p>
      <p>You will need administrative privileges ("root" privileges) on every platform to perform the installation of VirtualBox.</p>
      <p>Note: the latest tested version of VirtualBox working with CernVM is 4.3.14. If you have troubles with the latest verion of VirtualBox, pick that one: the full history of VirtualBox versions is available <a href="https://www.VirtualBox.org/wiki/Download_Old_Builds">on a different page.</a></p>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="gen-box">
      <h2 id="download">Step 2: Download a LHCb virtual machine and run</h2>
      <p>Download LHCb virtual machine from <a href="https://lhcbproject.web.cern.ch/lhcbproject/dist/Masterclass/vm/LHCbMasterclass.ova"> here</a></p>
      <p>Open it with VirtualBox. Once started there is a shortcut on the desktop to start the LHCb masterclass exercise itself</p>
      <div class="row">
        <img class="col-sm-6" src="{{url_for('static', filename='img/vm_lhcb_1.png')}}" alt="">
        <img class="col-sm-6" src="{{url_for('static', filename='img/vm_lhcb_2.png')}}" alt="">
      </div>
    </div>
  </div>
</div>
{% endblock %}

cernopendata/templates/cernopendata/VM/index.html
{%- extends config.BASE_TEMPLATE %}

{%- block page_body %}
<section class="general">
  <div class="container">
    <p class="lead">
      CERN Virtual Machines allow you to run Scientific Linux on any operating
      system and access the CERN working environments and software tools.
    </p>
    <div class="row">
      {% for e in config.OPENDATA_EXPERIMENTS %}
      {% if e != 'ATLAS' %}
      <div class="col-md-6">
        <div class="panel panel-default">
          <a href="{{ url_for('cernopendata.vm_experiment', experiment=e) }}">
            <div class="panel-body">
                <img src="{{ url_for('static', filename='img/'+e+'.gif') }}" alt=""
                    class="center-block" style="height: 15vh;">
            </div>
            <div class="panel-footer">
              <h3 class="text-center">
                {{ _('%(experiment)s Virtual Machines', experiment=e) }}
              </h3>
            </div>
          </a>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}

cernopendata/templates/cernopendata/VM/validation.html
{% extends "page.html" %}



{% block body %}

  <style>

    #vm_howto_content > .row {
      margin-bottom: 20px;
    }

    .tab-pane .about .title {
      font-weight: 600;
      font-size: 28px;
      padding-bottom: 30px;
    }

    .coll-exp .thumb {
      border-bottom: 1px solid #dfdfdf;
      padding-bottom: 20px;
    }
    .coll-exp .thumb img {
      height: 120px;
      padding: 5px;
      border-radius: 5px;
      font-size: 30px;
      font-weight: 100px;
    }

    .coll-exp .title span{
      float: left;
      font-size: 16px;
      font-weight: 400;

    }
    .coll-exp .other {
      padding-bottom: 25px;
      height: 100%;
      max-height: 150px;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .coll-exp .other span {
      height: 120px;
      text-overflow: ellipsis;
      overflow: hidden;
      display: block;
    }
    .coll-exp .exp-name {
      padding: 20px;
      font-size: 26px;
      font-weight: 100;
      color: #657580;
    }

    .coll-exp {
      background-color: #f4f4f4;
      padding: 30px;
      text-align: center;
      height: auto;
      display: inline-block;
      font-weight: 100;
      border-radius: 5px;
      color: #657580;
      margin-bottom: 20px;
      width: 100%;
    }

  </style>

  {% import 'helpers/general.html' as gen_utils %}
  {% with collection = 0 %}
    {% include 'search/form/index.html' %}
  {% endwith %}

  <section class="infobar">
    <div class="container">
      {{ gen_utils.get_breadcrumbs(breadcrumbs, exp, exp_names) }}
    </div>
  </section>

  <section class="general content">
    <div class="container">
      
      <div class="tab-content">
        <div class="tab-pane fade {% if exp not in exp_names %} in active {% endif %}" id="general">
          <div class="gen-header">
            <h1>CERN Virtual Machines allow you to run Scientific Linux on any operating system and access the CERN working environments and software tools.</h1>
          </div>
          <div class="row">
            {% for e in exp_names %}
            <div class="col-md-6">
              <a href="{{ url_for((request.path|splitthem)[1]+'/'+e) }}">
                <div class="coll-exp">
                  <div class="top col-md-12">
                    <div class="col-md-6 col-md-offset-3 thumb"><img src="{{ url_for('static', filename='img/'+e+'.gif') }}" alt="" class="img-cirle center-block"></div>
                    <div class="col-md-12 exp-name">{{e}} Virtual Machines</div>
                  </div>
                </div>
              </a>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="tab-pane fade {% if exp == 'CMS' %} in active {% endif %}" id="CMS">
          {% include 'helpers/text/vms_cms_page.html' %}
        </div>
        <div class="tab-pane fade {% if exp == 'ALICE' %} in active {% endif %}" id="ALICE">
          {% include 'helpers/text/vms_alice_page.html' %}
        </div>
        <div class="tab-pane fade {% if exp == 'LHCb' %} in active {% endif %}" id="LHCb">
          {% include 'helpers/text/vms_lhcb_page.html' %}
        </div>
      </div>

    </div>

  </section>


{% endblock %}

{%- block javascript %}
{{super()}}
<script>
$(document).ready(function() {
  // add a hash to the URL when the user clicks on a tab
  $('a[data-toggle="tab"]').on('click', function(e) {
    history.pushState(null, null, $(this).attr('href'));
  });
  // navigate to a tab when the history changes
  window.addEventListener("popstate", function(e) {
    var activeTab = $('[href="' + location.pathname + '"][data-toggle="tab"]');
    if (activeTab.length) {
      activeTab.tab('show');
    } else {
      $('.nav-tabs a:first').tab('show');
    }
  });
});
</script>
{% endblock %}